nav:
  title: Apsis
  blog: blog
  contact: contact

home:
  title: Apsis

  # Under construction section
  underConstruction:
    title: We're revamping our site!
    text: <p>In the meantime, feel free to read through our <a href="/blog">tech blog</a>.</p><p>Or <a href="/contact">drop us a note</a> to get in touch.</p>

blog:
  title: Apsis Tech Blog
  subtitle: Fun lessons learned in the land of technology
  blog: blog

contact:
  title: Contact us
  text: Fill the form below to get in touch with our team, we'll get back to you shortly.
  namePlaceholder: Name
  emailPlaceholder: Email
  messagePlaceholder: Message

  confirmation: Message sent! We'll get in touch with you soon.

  cta: Send message
  sending: Sending...
  sent: Message sent

  error:
    invalidName: Please type your name
    invalidEmail: Invalid email
    invalidMessage: Please tell us about your inquiry
    failure: Apologies, something went wrong. Please retry.

error:
  notFound:
    title: Page not found
    caption: Hmm... We couldn't find what you're looking for 🤔
