# Color themes

default:
  name: Apsis
  description: Apsis basic color theme

  light:
    --error-color: '#f90'
    --text-color: '#222'
    --highlighted-text-color: '#000'
    --muted-text-color: '#666'
    --background-color: '#eee'
    --background-color-callout: '#ddd'
    --border-color: '#aaa'

  dark:
    --error-color: '#f90'
    --text-color: '#ddd'
    --highlighted-text-color: '#fff'
    --muted-text-color: '#aaa'
    --background-color: '#222'
    --background-color-callout: '#333'
    --border-color: '#555'

superuva:
  name: Superuva
  description: Deep purple theme

  light:
    --error-color: '#f70'
    --text-color: '#203'
    --highlighted-text-color: '#102'
    --muted-text-color: '#5c5062'
    --background-color: '#f5f8ff'
    --background-color-callout: '#e8ecf3'
    --border-color: '#8f98a3'
    --main-gradient: 'linear-gradient(130deg, #f07 10%, #70f 80%)'

  dark:
    --error-color: '#f70'
    --text-color: '#f2f1f4'
    --highlighted-text-color: '#f5f5ff'
    --muted-text-color: '#b1abba'
    --background-color: '#110b1b'
    --background-color-callout: '#22192e'
    --border-color: '#5e5775'
    --main-gradient: 'linear-gradient(130deg, #f07 10%, #70f 80%)'
