authors:
  Martin:
    name: Martin Zenzerovich
    photoUrl: /img/team/martin.jpg
    linkedin: https://www.linkedin.com/in/martinzenzerovich/
    twitter: https://twitter.com/MartinZenz

  Fabricio:
    name: Fabricio Blas
    photoUrl: /img/team/fabricio.jpg
    linkedin: https://www.linkedin.com/in/fabricio-blas-bb16b417a/
