authors:
  Martin:
    name: Martin Zenzerovich
    photoUrl: /img/team/martin.jpg
    profileUrl: https://www.linkedin.com/in/martinzenzerovich/

  Fabricio:
    name: Fabricio Blas
    photoUrl: /img/team/fabricio.jpg
    profileUrl: https://www.linkedin.com/in/fabricio-blas-bb16b417a/
