company: Apsis Technologies
companyShort: Apsis

nav:
  blog: blog
  contact: contact

footer:
  notice: All rights reserved.

landing:
  description: Product development and design solutions.

blog:
  title: Apsis Blog
  subtitle: Fun lessons learned in the land of technology
  blog: blog
  footer:
    cta: Get in touch

contact:
  title: Contact us
  text1: Need help getting your project launched? We'd love to talk! Drop us a line with your info below, we'll get back to you in no time.
  text2: Can't wait to hear about your earth-shattering project!
  text3: You can also write to us to <a href="mailto:{EMAIL}">{EMAIL}</a>.

  namePlaceholder: Name
  emailPlaceholder: Email
  messagePlaceholder: Message

  confirmation: Message sent! We'll get in touch with you soon.

  cta: Send
  sending: Sending...
  sent: Sent!

  error:
    invalidName: Please type your name
    invalidEmail: Invalid email
    invalidMessage: Please tell us about your inquiry
    failure: Apologies, something went wrong. Please retry.

error:
  # used for notifying user about global app errors and crashes
  globalHandler: We just hit a snag, please retry...

  notFound:
    title: Page not found
    caption: Hmm... We couldn't find what you're looking for 🤔
