company:
  name: RockinDev
  tagline: Advanced digital solutions with a soul.
  locations:
    us: United States
    ba: Buenos Aires

locale: en_US

nav:
  jobs: jobs
  team: team
  blog: blog
  contact: contact us

footer:
  notice: All rights reserved.

team:
  title: Rockin' team
  description:
    - We are a team of forward-thinking technologists and creative professionals with deep expertise in product building and design. We absolutely love what we do and it shows.
    - Meet the team that makes it all happen.


blog:
  title: Rockin tech blog
  subtitle: Fun lessons learned in the land of technology.
  blog: blog
  footer:
    cta: Get in touch

contact:
  title: Get in touch
  message: Chat with us today to fast-track your development project. Just leave us a message below or email us at <a href="mailto:{EMAIL}">{EMAIL}</a>, we'll get back to you shortly to discuss your project needs.

  namePlaceholder: Name
  emailPlaceholder: Work email
  companyPlaceholder: Company
  messagePlaceholder: Message

  confirmation: Message sent! We'll get in touch with you soon.

  cta: Send
  sending: Sending...
  sent: Sent!

  error:
    invalidName: Please type your name
    invalidEmail: Invalid email
    invalidMessage: Please tell us about your inquiry
    failure: Apologies, something went wrong. Please retry.

error:
  # used for notifying user about global app errors and crashes
  globalHandler: We just hit a snag, please retry...

  notFound:
    title: Page not found
    caption: Hmm... We couldn't find what you're looking for. 🤔
    home: take me home
